import type { Metadata } from "next";
import localFont from "next/font/local";
import {Poppins} from 'next/font/google'
import "./globals.css";
import ClientLayout from "@/components/shared/ClientLayout";
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets:["latin"],
  weight:"500"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <ClientLayout>
          {children}
        </ClientLayout>
        <Toaster />
      </body>
    </html>
  );
}
